version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"
      include: "scope"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Ignore example app specific packages to prevent noise
      - dependency-name: "react"
      - dependency-name: "react-native*"
      - dependency-name: "@react-navigation/*"
      - dependency-name: "expo*"
      - dependency-name: "groq-sdk"
