# These rules configure the PR labeler workflow
# Map labels to path patterns

area: cli:
  - changed-files:
    - any-glob-to-any-file: 'packages/exis/src/cli/**/*'
    - any-glob-to-any-file: 'packages/create-exis/**/*'

area: core:
  - changed-files:
    - any-glob-to-any-file: 'packages/exis/src/server/**/*'
    - any-glob-to-any-file: 'packages/exis/src/router/**/*'
    
area: middleware:
  - changed-files:
    - any-glob-to-any-file: 'packages/exis/src/middleware/**/*'

area: docs:
  - changed-files:
    - any-glob-to-any-file: 'docs/**/*'
    - any-glob-to-any-file: 'README.md'

area: github-actions:
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'
