import { scrypt, randomBytes, timingSafeEqual } from 'node:crypto'

const scryptAsync = (
  password: string | Buffer,
  salt: string | Buffer,
  keylen: number,
  options?: import('node:crypto').ScryptOptions
): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    if (options) {
      scrypt(password, salt, keylen, options, (err, derivedKey) => {
        if (err) reject(err)
        else resolve(derivedKey)
      })
    } else {
      scrypt(password, salt, keylen, (err, derivedKey) => {
        if (err) reject(err)
        else resolve(derivedKey)
      })
    }
  })
}

export interface HashOptions {
  /** The length of the salt in bytes. Default: 16 */
  saltLength?: number
  /** The length of the derived key in bytes. Default: 64 */
  keyLength?: number
  /** CPU/memory cost parameter (N). Must be a power of 2 greater than 1. Default: 16384 */
  cost?: number
  /** Block size parameter (r). Default: 8 */
  blockSize?: number
  /** Parallelization parameter (p). Default: 1 */
  parallelization?: number
}

const DEFAULT_OPTIONS: Required<HashOptions> = {
  saltLength: 16,
  keyLength: 64,
  cost: 16384,
  blockSize: 8,
  parallelization: 1,
}

/**
 * Hash a password using scrypt.
 * Returns a string formatted as: `scrypt:N:r:p:keylen:salt:hash`
 * This ensures the options are securely stored alongside the hash for future verification.
 */
export async function hashPassword(
  password: string,
  options?: HashOptions
): Promise<string> {
  const opts = { ...DEFAULT_OPTIONS, ...options }
  const salt = randomBytes(opts.saltLength).toString('hex')

  const derivedKey = (await scryptAsync(password, salt, opts.keyLength, {
    N: opts.cost,
    r: opts.blockSize,
    p: opts.parallelization,
  })) as Buffer

  // Store the parameters used to create the hash so we can verify it later
  // Format: scrypt:cost:blockSize:parallelization:keyLength:salt:hash
  return `scrypt:${opts.cost}:${opts.blockSize}:${opts.parallelization}:${opts.keyLength}:${salt}:${derivedKey.toString('hex')}`
}

/**
 * Verify a password against a stored scrypt hash.
 * @param password The plaintext password to verify.
 * @param storedHash The stored hash string generated by `hashPassword`.
 */
export async function verifyPassword(
  password: string,
  storedHash: string
): Promise<boolean> {
  if (!password || !storedHash || typeof storedHash !== 'string') {
    return false
  }

  // Backwards compatibility with the old simple format `salt:hash`
  const parts = storedHash.split(':')

  if (parts.length === 2) {
    const [salt, key] = parts
    if (!salt || !key) return false
    const keyBuffer = Buffer.from(key, 'hex')
    const derivedKey = (await scryptAsync(password, salt, 64)) as Buffer
    if (keyBuffer.length !== derivedKey.length) return false
    return timingSafeEqual(keyBuffer, derivedKey)
  }

  // New format: scrypt:N:r:p:keylen:salt:hash
  if (parts.length === 7 && parts[0] === 'scrypt') {
    const cost = parseInt(parts[1], 10)
    const blockSize = parseInt(parts[2], 10)
    const parallelization = parseInt(parts[3], 10)
    const keyLength = parseInt(parts[4], 10)
    const salt = parts[5]
    const key = parts[6]

    if (!salt || !key) return false

    const keyBuffer = Buffer.from(key, 'hex')
    const derivedKey = (await scryptAsync(password, salt, keyLength, {
      N: cost,
      r: blockSize,
      p: parallelization,
    })) as Buffer

    if (keyBuffer.length !== derivedKey.length) return false
    return timingSafeEqual(keyBuffer, derivedKey)
  }

  return false
}
