import * as path from 'node:path'
import * as fs from 'node:fs/promises'
import * as crypto from 'node:crypto'

export async function generateManifest(
  cwd: string,
  outDir: string,
  isDev = false
): Promise<void> {
  const exisDir = path.join(cwd, '.exis')

  // Ensure .exis exists
  try {
    await fs.mkdir(exisDir, { recursive: true })
  } catch {
    // ignore
  }

  // Find the api directory inside outDir
  const searchDirs = isDev
    ? [path.join(cwd, 'src', 'http'), path.join(cwd, 'http')]
    : [path.join(cwd, outDir, 'src', 'http'), path.join(cwd, outDir, 'http')]

  let apiDir = ''
  for (const dir of searchDirs) {
    try {
      const stat = await fs.stat(dir)
      if (stat.isDirectory()) {
        apiDir = dir
        break
      }
    } catch {
      /* ignore */
    }
  }

  if (!apiDir) {
    return
  }

  const routes = await scanDirectory(apiDir, '/')
  const validRoutes = routes.filter(
    (r) => r.filePath.endsWith('route.ts') || r.filePath.endsWith('route.js')
  )

  let importLines = ''
  let exportLines = 'export const manifest = [\n'

  let typeImportLines = ''
  let typeExportLines = 'export type AppRouter = {\n'

  for (let i = 0; i < validRoutes.length; i++) {
    const route = validRoutes[i]
    // The path to import inside .exis/routes-manifest.js needs to be relative to .exis
    // But since .exis is at root, and route.filePath is absolute,
    // we make it relative from .exis to the route file
    let relativePath = path
      .relative(exisDir, route.filePath)
      .replace(/\\/g, '/')
    if (!relativePath.startsWith('.')) {
      relativePath = './' + relativePath
    }

    // Convert .ts to .js for imports in production
    if (!isDev) {
      relativePath = relativePath.replace(/\.ts$/, '.js')
    }

    const moduleName = `route_${i}`
    importLines += `import * as ${moduleName} from '${relativePath}'\n`

    // For types, we always import the .ts (or omit extension so TS resolves it)
    const typeRelativePath = relativePath.replace(/\.(js|ts)$/, '')
    typeImportLines += `import type Route${i} from '${typeRelativePath}'\n`

    // Compute content hash for invalidation
    const content = await fs.readFile(route.filePath, 'utf8')
    const hash = crypto
      .createHash('sha256')
      .update(content)
      .digest('hex')
      .substring(0, 8)

    // Store routePath, module, and the original file path (relative to root) for debugging/logging
    const rootRelativePath = path
      .relative(cwd, route.filePath)
      .replace(/\\/g, '/')
    exportLines += `  { routePath: '${route.routePath}', module: ${moduleName}, filePath: '${rootRelativePath}', hash: '${hash}' },\n`

    typeExportLines += `  '${route.routePath}': typeof Route${i} extends { __type: infer T } ? T : never\n`
  }

  exportLines += ']\n'
  typeExportLines += '}\n'

  const manifestContent = `// Automatically generated by Exis\n\n${importLines}\n${exportLines}`

  if (!isDev) {
    await fs.writeFile(
      path.join(exisDir, 'routes-manifest.js'),
      manifestContent,
      'utf8'
    )
  } else {
    // Delete stale manifest in dev mode so the app uses lazy loading
    try {
      await fs.unlink(path.join(exisDir, 'routes-manifest.js'))
    } catch {
      // ignore
    }
  }

  const typesContent = `// Automatically generated by Exis\n\n${typeImportLines}\n${typeExportLines}`
  await fs.writeFile(path.join(exisDir, 'types.d.ts'), typesContent, 'utf8')

  // Write dev diagnostics into .exis so external tools can consume it
  if (isDev) {
    const devStatus = {
      generatedAt: new Date().toISOString(),
      routeCount: validRoutes.length,
      routes: validRoutes.map((r) => ({
        path: r.routePath,
        file: path.relative(cwd, r.filePath).replace(/\\/g, '/'),
      })),
      status: 'ok',
    }
    await fs.writeFile(
      path.join(exisDir, 'dev-status.json'),
      JSON.stringify(devStatus, null, 2),
      'utf8'
    )
  }

  await generateExisEnv(cwd)
}

async function scanDirectory(
  dir: string,
  baseRoute = '/'
): Promise<{ filePath: string; routePath: string }[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true })
  const results: { filePath: string; routePath: string }[] = []

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      let segment = entry.name

      if (segment.startsWith('(') && segment.endsWith(')')) {
        const subResults = await scanDirectory(fullPath, baseRoute)
        results.push(...subResults)
        continue
      }

      if (segment.startsWith('[...') && segment.endsWith(']')) {
        segment = '*' + segment.slice(4, -1)
      } else {
        segment = segment.replace(/\[(.*?)\]/g, ':$1')
      }

      const nextBase =
        baseRoute === '/' ? `/${segment}` : `${baseRoute}/${segment}`
      const subResults = await scanDirectory(fullPath, nextBase)
      results.push(...subResults)
    } else {
      results.push({ filePath: fullPath, routePath: baseRoute })
    }
  }
  return results
}

export async function generateExisEnv(cwd: string): Promise<void> {
  const isTsProject = await fs
    .access(path.join(cwd, 'tsconfig.json'))
    .then(() => true)
    .catch(() => false)

  if (!isTsProject) return

  const hasNodeTypes = await fs
    .access(path.join(cwd, 'node_modules', '@types', 'node'))
    .then(() => true)
    .catch(() => false)

  let envContent = `/// <reference types="exisjs" />

// NOTE: This file should not be edited
// It is automatically generated by ExisJS

// Exposes your compiled routes to the TypeScript server
import type { AppRouter } from './.exis/types'
`

  if (!hasNodeTypes) {
    envContent += `
// Fallback types for production builds where @types/node is pruned
declare var process: any;
declare var console: any;
declare var Buffer: any;
declare var __dirname: string;
declare var __filename: string;
declare var module: any;
declare var exports: any;
declare var require: any;
declare module 'node:*' {
  const x: any;
  export = x;
}
declare module 'fs' {
  const x: any;
  export = x;
}
declare module 'fs/promises' {
  const x: any;
  export = x;
}
declare module 'path' {
  const x: any;
  export = x;
}
declare module 'crypto' {
  const x: any;
  export = x;
}
declare module 'http' {
  const x: any;
  export = x;
}
declare module 'child_process' {
  const x: any;
  export = x;
}
`
  }

  await fs.writeFile(path.join(cwd, 'exis.d.ts'), envContent, 'utf8')
}
