/// <reference types="exisjs" />

// NOTE: This file should not be edited
// It is automatically generated by ExisJS

// Exposes your compiled routes to the TypeScript server
import type { AppRouter } from './.exis/types'
