name: Trigger Release

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build Packages
        run: npm run build
        
      - name: Publish exisjs
        run: npm publish --access public
        working-directory: packages/exis
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Publish @exisjs/create
        run: npm publish --access public
        working-directory: packages/create-exis
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @exisjs/client
        run: npm publish --access public
        working-directory: packages/client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
